bugcrowd/vrt-ruby

.gitmodules, Gemfile.lock, lib/vrt/version.rb
I will push the new release to rubygems after this PR is merged.
=> Add VRT version 1.3 and bump Vrt::VERSION

Gemfile.lock, README.md, bin/console, vrt.gemspec
Good to be able to have an interactive console to mess around with:
=> [CHORE] Add an interactive console for the gem and add pry as a development dependency

lib/vrt/map.rb, spec/vrt/map_spec.rb
Validation function was weak. This toughens it up a bit.
=> More robustly validate full VRT ids passed to Map

Gemfile.lock, lib/vrt/version.rb
Bump version number to hopefully fix an issue with deploying this gem to rubygems
=> Release v0.4.2

Gemfile.lock, lib/vrt.rb, lib/vrt/cross_version_mapping.rb, lib/vrt/version.rb, spec/vrt_spec.rb
Added subcategories to `cross_version_category_mapping`
And use them in `VRT.all_matching_categories`
Added spec for changes.
=> [BC-7978] Add support for subcategory filtering

.github/PULL_REQUEST_TEMPLATE.md
Pretty self explanatory, hopefully just allow us to stop answering recurring questions
=> [CHORE] Add a pull request template

CHANGELOG.md, lib/vrt/mapping.rb, spec/sample_vrt/999.999/mappings/test_mapping.json, spec/vrt/mappings_spec.rb
dig or dig not.
resolves: https://github.com/bugcrowd/vrt-ruby/issues/26
=> There is no try

.gitmodules, CHANGELOG.md, lib/vrt/version.rb
=> Vrt version 1.5

CONTRIBUTING.md
Update the Contributing doc to de-dupe our internal documents
=> Add release process clarity

.gitmodules, CHANGELOG.md
Updates submodule version for taxonomy
=> Update the taxonomy version to 1.7

.gitmodules, CHANGELOG.md
Updates latest vrt version to 1.7.1 to include automotive mappings
=> Add vrt 1.7.1 auto mappings

README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
- [N/A] I have made corresponding changes to the documentation
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] I have added entries to `CHANGELOG.md` and marked it Added/Changed/Removed
- [N/A] I have not incremented `version.rb`
=> badges: add doc + links

.github/workflows/build.yml, .github/workflows/build_and_test.yml, .gitignore, README.md, vrt.gemspec
Updates bundler version version to `~> 2.1`
Updates build badge to use github actions badge
=> Update bundler config

.github/workflows/build.yml
Add explicit support for ruby 2.7
=> Add ruby 2.7 to testing matrix

README.md
Logo pixels are too big, using an svg instead of png.
=> Update logo to svg

.gitmodules
This is to pull in the new vrt version v1.11 as a submodule in data.
=> V0.12.0 release

CHANGELOG.md, lib/vrt/version.rb
This is to pull in the new vrt version v1.11 as a submodule in data along with some minor fixes in VRT
=> v0.12.1 release

CHANGELOG.md, lib/vrt/version.rb
Support for v1.11 VRT with some fixes
=> V0.12.2 release

.gitmodules, CHANGELOG.md, lib/vrt/version.rb
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> v0.12.3 release for vrt v1.12

CHANGELOG.md, lib/vrt/version.rb
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> VRT 1.11 fix

.gitmodules, CHANGELOG.md, lib/vrt.rb, lib/vrt/version.rb
VRT 1.13 release. Adding VRT for Physical and Hardware security.
=> v0.12.6 Release

.gitmodules, CHANGELOG.md, lib/vrt/version.rb
=> v0.12.7 release

.github/workflows/build.yml, .rubocop.yml, Dockerfile, lib/vrt.rb, lib/vrt/cross_version_mapping.rb, lib/vrt/map.rb, lib/vrt/mapping.rb, lib/vrt/node.rb, lib/vrt/third_party_links.rb, spec/vrt_spec.rb, vrt.gemspec
Changing Ruby version to 3.1 (Current least supported version of Ruby)
* Includes upgrading various gems specified in tha gemspec
Please note- This is just ruby version upgrade, part 2 will contain the VRT Update as well.
=> v0.13.0 Release: Ruby Version Upgrade Part #1

CHANGELOG.md, lib/vrt/version.rb
Minor bugfixes
- [x ] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added entries to `CHANGELOG.md` and marked it Added/Changed/Removed
- [x ] I have not incremented `version.rb`
=> vrt-ruby v0.13.1 release

.gitmodules, CHANGELOG.md, lib/vrt/version.rb
This is to pull in the new VRT version v1.14.2 as a submodule in data.
=> Update VRT version 1.14.2
